language: java
jdk:
- oraclejdk8
sudo: false
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: gATq3pMvh9vhYBsqno+Q3e8Q91IqUGFnKZy4aLNxm5+FeUvo+mqKr8zxA9UnM4fa5aicPLi0fbDNuPkoPC++PX9Lo0xvPI7g0Z3bxwlWmwGuZDY1t1VPWF9uIlE59ILZLUxOtv8BwysBUdkAqXITx9vkrCk4/rzcptcZpkktkURpCPcnZhfF8rgjuu4N/b23Y96bI2jTEik7Wgawk1ITi5iw35vs06szqMxnpOfMWDOlDumraA5uPjGXOmqDI202ABTKkAdSjZX8/xm/1A7Qx0TvWiQEK4J6Vr0Jg4xJnlv1grqHiaoASdxdKqP3NCGNuGmzhLS3l3ogjHumiRAuh4Cu9bGaDu9TJA+NuVW22LbL+Gj+7vCa8LTozw83sD7AnpOP+bl4VEK3SKF3OF5EwaqPtqq0+WTel2N+znQQ2zKSRXdiln7PHX1IC4wRiYbG6vj/PyWk81Grxlh7tzzNsvCBDRg+9VnM7O3wS4zEq5Hz9cXDCvMyb9rogwSIoMvQ32PY5BdbBAjJxnSpBybeFg2Po3UITwNaUwaagBnxxapsWJokjpDva/vVbbeqbtyJoEOirfLxztq4rCGn4uSdeoiZy1SbM0gWTVKSPJy/eQW9gNUjA9TOZZkBWtsy51n255qQCpNYo6uhrEixp98jJf+xpSFFpO7bBMpHQpJ/Vng=
  - secure: Y2oirbA1TLcw+Jjn7+8niJ1OaOAQWanC2f9mTjI7e9RCbdSwwhQjsLNjxDcaM30ZHAY00Mzw/vIYJlHggRvgM/qp5xM6h5fMs54HLB5pV0aoQy6p8znK08dtkpgRWXbi2quiCGCphkQAQPq0y6fqzGTXFiP+D/nFoEp2/XJlViz8HddJKiEt9aV8SD8cImIswUtU85GksgJKm9Zp+I7dSkZ0i0nENpsaLqqMkr5WdhaPTHMintZtGZjGq7OeGTI7LnaH2xXEGLIj/jTSM71AkmSx+TyIrdspDXXz2jGfR+eZtc0bnRI26MXvgE14kH9nWdrX2Mwg6rqQnresCky8KcQtOh5cgj1MZzkQfA3yizIN1d7H7+mgaFz/Pep3V9gQnwDVdWApl1RHgv8Efnrp9kpil3O7DSGoRzHlxFoP3JolmP2EYU/lGcCLdnE3O4XZTXULTXzZmjrbk16dFlOtT0xAzbQj2CLl66iEcwqmzIOjFAgmjxO7MmZRSuEDNTZU+uhSRg8dNK1mO2YcqViz3KYKTjVDnasA/noeZMpao6ey+pP2+pUVJmM9lZJIuw4Y7l2qvTanFVVOzi0pqKeuL1Ig0Bsp8ikFPVADIio0KcxLB6DJTIP+MKOExvE8Stit4rr/hnvaqZ5En2EDZetA0qtvfSMbb6VV9P4OYuk2JS0=
