language: java
jdk:
- oraclejdk8
sudo: false
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: e6PIRe1teHzY7JcBSaV2o5Q19wULNI01uJvt5WkqGcvEuhPZTVeHEc6qq703x8NqdNmfFDvY5lYni4SeN2d4aSu113+CUD5O+Vhn3nSot3GSNWXJC08YTqCxh8EkLMI/302Vjv9SIDN8QgmCtCb3X4EVdjxrV2rGdHGvVv30Jx/Z6Xj26SNwqI0zriPA3Bx1ym3zaAN7VP/UDbl37BSWdAlBVYMAQCuA1TEiiKUMNZFl3PJ1x0/nd+Ql8J6X9MYkDsS9sAQU39O9CESTMfo6920XWzB5g3G7ZQ0W03iklGbpgIgAK/FthxmP6Ugzp4q9IlD7t14RMvP2bHUF7SapPssHieh3GWyZUqkE2dO7opg8bAwEDzJnQ0+Vxw5e1vDgvgMQK2XirOIumeJZtTsLqz3iDM2BOVBbMOwXaM85umGfGOSL74ayOjmyj2Uv1hkOFbg6DG7y9F+iXkycpPnVec5ROTWC2cRpfNDPc9H3tdHsQKn7IcxDzjh//xSgrbKU1fdH8m1rHXqrZn3zCh0x5bX2Bk98ITT27/IripLF1qwp1QuP7Z9SS2x1On7ALhF2Ix9vjbnVF/uEgeRQoKANgNi/phDBUX3NGer12OKzgCXdJ1H+RBsw1khNQhI2Y4vZDT3aevLPvsxtLkLn9kmUlkN1MwI22+HSzRdBZTY/Ous=
  - secure: cuIppGXdX/tEooebXl5QDb76G2eOxwO5UQfoOFyaqyZ+GtriBMEKXUqmiz82PPoKlZtf3p3uGwgikoH71VdA1cxvmBHmSkHK+4zWNLUx0uHmCVzPUltHMF0zYJ8SuWo7CbY8HQAT+BIZQIe7Yr1T8F0YWFwaSjGay1/Lq+ioOCIoeMclHiZcpT3zHyPkhPKcxljDFjWrS7etuoCJ4yMfJ96Esi79eSiD3lhFHmwl36tDVy7wB6SBRZ4X/W3NZtjEd9XEPwUSxpsNz4utIpUkhm+NUwZP8zFd8+BdLl3VP/bj3ulnx2BBCQtkMcCDLCs1/pkIOlO3czIJl9X6kdSxky/muK72ngvfiBpAm8evm+kA2kiKmcDdU7VSpBYwtJTyTEoScbWwe09FNxdG6gcSLenWQ88v618Vi02dPMrU9EifMnTViTE6eVy3m4/oQLWWg2xrivu7AKlbkSu4jERSDZ/Tcwb9WkKZEY0yzX/8oaPTgP1mSPoUeTPoPiEVprDIKY9k+GdddZbux0POPmWFX0gj2cuh0zFImHJQRst0DNg2tbYm6PeD83IDb9iRgjzMZQPqZJQPqtz7ESZZW5cWqfHVetyYK01cLoMscaNi9V160GZb8vjy5oKGaLnA1h+UeViXdPvm+U2NR4xqoojsNVZr7h+nHQ00naT1fVqM0UM=
